package org.schabi.newpipe.extractor.services.iwara;

import com.grack.nanojson.JsonArray;
import com.grack.nanojson.JsonObject;
import com.grack.nanojson.JsonParser;
import org.schabi.newpipe.extractor.*;
import org.schabi.newpipe.extractor.bulletComments.BulletCommentsExtractor;
import org.schabi.newpipe.extractor.channel.*;
import org.schabi.newpipe.extractor.comments.CommentsExtractor;
import org.schabi.newpipe.extractor.downloader.*;
import org.schabi.newpipe.extractor.exceptions.*;
import org.schabi.newpipe.extractor.kiosk.*;
import org.schabi.newpipe.extractor.linkhandler.*;
import org.schabi.newpipe.extractor.playlist.PlaylistExtractor;
import org.schabi.newpipe.extractor.search.*;
import org.schabi.newpipe.extractor.search.filter.FilterItem;
import org.schabi.newpipe.extractor.stream.*;
import org.schabi.newpipe.extractor.subscription.SubscriptionExtractor;
import org.schabi.newpipe.extractor.suggestion.SuggestionExtractor;
import java.io.IOException; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.util.*;
import javax.annotation.Nonnull; import javax.annotation.Nullable;

/** Public Iwara API extractor. */
public final class IwaraService extends StreamingService {
 public IwaraService(int id){super(id,"Iwara",Collections.singletonList(ServiceInfo.MediaCapability.VIDEO));}
 public String getBaseUrl(){return P.WEB;} public LinkHandlerFactory getStreamLHFactory(){return F.INSTANCE;} public ListLinkHandlerFactory getChannelLHFactory(){return null;} public ListLinkHandlerFactory getChannelTabLHFactory(){return null;} public ListLinkHandlerFactory getPlaylistLHFactory(){return null;} public SearchQueryHandlerFactory getSearchQHFactory(){return SF.INSTANCE;} public ListLinkHandlerFactory getCommentsLHFactory(){return null;} public SearchExtractor getSearchExtractor(SearchQueryHandler h){return new S(this,h);} public SuggestionExtractor getSuggestionExtractor(){return null;} public SubscriptionExtractor getSubscriptionExtractor(){return null;} public ChannelExtractor getChannelExtractor(ListLinkHandler h){return null;} public ChannelTabExtractor getChannelTabExtractor(ListLinkHandler h)throws ExtractionException{throw new ExtractionException("Iwara channels unavailable");} public PlaylistExtractor getPlaylistExtractor(ListLinkHandler h)throws ExtractionException{throw new ExtractionException("Iwara playlists unavailable");} public StreamExtractor getStreamExtractor(LinkHandler h){return new V(this,h);} public CommentsExtractor getCommentsExtractor(ListLinkHandler h){return null;} public BulletCommentsExtractor getBulletCommentsExtractor(ListLinkHandler h){return null;}
 public KioskList getKioskList()throws ExtractionException{try{KioskList k=new KioskList(this);k.addKioskEntry((s,u,id)->new K(s,KF.INSTANCE.fromId(id),id),KF.INSTANCE,"trending");k.setDefaultKiosk("trending");return k;}catch(Exception e){throw new ExtractionException("Iwara kiosk",e);}}
}
final class F extends LinkHandlerFactory {static final F INSTANCE=new F(); public String getId(String u)throws ParsingException{return P.id(u);} public String getUrl(String id){return P.WEB+"/video/"+id;} public boolean onAcceptUrl(String u){return u!=null&&u.contains("iwara.tv/video/");}}
final class SF extends SearchQueryHandlerFactory {static final SF INSTANCE=new SF(); public String getUrl(String q,List<FilterItem>c,List<FilterItem>s){return P.search(q,0);}}
final class KF extends ListLinkHandlerFactory {static final KF INSTANCE=new KF(); public String getId(String u){return "trending";} public String getUrl(String id,List<FilterItem>c,List<FilterItem>s){return P.API+"/trending/video?rating=all&limit=24";} public boolean onAcceptUrl(String u){return true;}}
final class S extends SearchExtractor {S(StreamingService s,SearchQueryHandler h){super(s,h);} public void onFetchPage(@Nonnull Downloader d){} protected InfoItemsPage<InfoItem> getInitialPageInternal()throws IOException,ExtractionException{return page(0);} protected InfoItemsPage<InfoItem> getPageInternal(Page p)throws IOException,ExtractionException{return page(P.number(p));} private InfoItemsPage<InfoItem> page(int n)throws IOException,ExtractionException{JsonObject o=P.json(P.search(getSearchString(),n));MultiInfoItemsCollector c=new MultiInfoItemsCollector(getServiceId());for(Object x:o.getArray("results"))c.commit(new I((JsonObject)x));return new InfoItemsPage<>(c,o.getArray("results").size()>=32?new Page(String.valueOf(n+1)):null);}}
final class K extends KioskExtractor<StreamInfoItem>{K(StreamingService s,ListLinkHandler h,String id){super(s,h,id);} public void onFetchPage(@Nonnull Downloader d){} @Nonnull public String getName(){return "Trending";} @Nonnull public InfoItemsPage<StreamInfoItem> getInitialPage()throws ExtractionException{try{StreamInfoItemsCollector c=new StreamInfoItemsCollector(getServiceId());for(Object x:P.json(getUrl()).getArray("results"))c.commit(new I((JsonObject)x));return new InfoItemsPage<>(c,null);}catch(Exception e){throw new ExtractionException("Iwara trending",e);}} public InfoItemsPage<StreamInfoItem> getPage(Page p){return new InfoItemsPage<>(new StreamInfoItemsCollector(getServiceId()),null);}}
final class V extends StreamExtractor {JsonObject data; V(StreamingService s,LinkHandler h){super(s,h);} public void onFetchPage(@Nonnull Downloader d)throws IOException,ExtractionException{data=P.json(P.API+"/video/"+getId());} void ok()throws ParsingException{if(data==null)throw new ParsingException("Iwara video not fetched");} @Nonnull public String getName()throws ParsingException{ok();return data.getString("title");} @Nonnull public String getThumbnailUrl()throws ParsingException{ok();JsonObject f=data.getObject("file");return P.thumb(f,data.getInt("thumbnail"));} @Nonnull public Description getDescription()throws ParsingException{ok();String b=data.getString("body");return b==null?Description.EMPTY_DESCRIPTION:new Description(b,Description.PLAIN_TEXT);} public long getLength()throws ParsingException{ok();JsonObject f=data.getObject("file");return f==null?-1:f.getLong("duration",-1);} @Nonnull public String getUploaderName()throws ParsingException{ok();return data.getObject("user").getString("name");} @Nonnull public String getUploaderUrl(){return P.WEB+"/";} @Nonnull public List<String> getTags()throws ParsingException{ok();List<String>r=new ArrayList<>();for(Object x:data.getArray("tags"))r.add(((JsonObject)x).getString("id"));return r;} public String getTextualUploadDate(){return "";} public List<AudioStream> getAudioStreams(){return Collections.emptyList();} public List<VideoStream> getVideoStreams()throws IOException,ExtractionException{ok();String u=data.getString("fileUrl");if(u==null||u.isEmpty())throw new ParsingException("No Iwara file URL");final LinkedHashMap<String,VideoStream> streams=new LinkedHashMap<>();for(Object value:P.array(u)){final JsonObject item=(JsonObject)value;final JsonObject src=item.getObject("src");if(src==null)continue;final String media=P.absolute(src.getString("view"));if(media.isEmpty())continue;final String quality=item.getString("name");streams.put(media,new VideoStream.Builder().setId(quality).setContent(P.mark(media,getUrl()),true).setResolution(quality).setMediaFormat(MediaFormat.MPEG_4).setDeliveryMethod(DeliveryMethod.PROGRESSIVE_HTTP).setIsVideoOnly(false).build());}if(streams.isEmpty())throw new ParsingException("No playable Iwara media URL");return new ArrayList<>(streams.values());} public List<VideoStream> getVideoOnlyStreams(){return Collections.emptyList();} public StreamType getStreamType(){return StreamType.VIDEO_STREAM;} public InfoItemsCollector<? extends InfoItem,? extends InfoItemExtractor> getRelatedItems()throws IOException,ExtractionException{ok();StreamInfoItemsCollector c=new StreamInfoItemsCollector(getServiceId());for(Object x:P.json(P.API+"/video/"+getId()+"/related").getArray("results"))c.commit(new I((JsonObject)x));return c;} @Nonnull public List<MetaInfo> getMetaInfo(){return Collections.emptyList();}}
final class I implements StreamInfoItemExtractor {final JsonObject o;I(JsonObject o){this.o=o;} JsonObject f(){return o.getObject("file");} public String getName(){return o.getString("title");} public String getUrl(){return P.WEB+"/video/"+o.getString("id");} public String getThumbnailUrl(){return P.thumb(f(),o.getInt("thumbnail"));} public StreamType getStreamType(){return StreamType.VIDEO_STREAM;} public long getDuration(){JsonObject f=f();return f==null?-1:f.getLong("duration",-1);} public long getViewCount(){return o.getLong("numViews",-1);} public String getUploaderName(){JsonObject u=o.getObject("user");return u==null?"Iwara":u.getString("name");} public String getUploaderUrl(){return P.WEB+"/";} @Nullable public String getTextualUploadDate(){return null;} @Nullable public org.schabi.newpipe.extractor.localization.DateWrapper getUploadDate(){return null;}}
final class P {static final String WEB="https://www.iwara.tv",API="https://api.iwara.tv",VERSION="b25f20ee9a87452f0c4b36e4bd53264b4eb37f46"; static JsonObject json(String u)throws IOException,ExtractionException{Response r=NewPipe.getDownloader().get(u,h());if(r.responseCode()!=200)throw new ParsingException("Iwara API HTTP "+r.responseCode());try{return JsonParser.object().from(r.responseBody());}catch(Exception e){throw new ParsingException("Invalid Iwara API response",e);}} static JsonArray array(String u)throws IOException,ExtractionException{Response r=NewPipe.getDownloader().get(u,h());if(r.responseCode()!=200)throw new ParsingException("Iwara file API HTTP "+r.responseCode());try{return JsonParser.array().from(r.responseBody());}catch(Exception e){throw new ParsingException("Invalid Iwara file response",e);}} static String absolute(String u){if(u==null)return "";return u.startsWith("//")?"https:"+u:u;} static String id(String u)throws ParsingException{int i=u.indexOf("/video/");if(i<0)throw new ParsingException("Invalid Iwara URL");String x=u.substring(i+7).split("[/?#]",2)[0];if(x.isEmpty())throw new ParsingException("Invalid Iwara ID");return x;} static String search(String q,int p){return API+"/search?type=videos&page="+p+"&query="+enc(q);} static int number(Page p){try{return Integer.parseInt(p.getId());}catch(Exception e){return 0;}} static String thumb(JsonObject f,int n){if(f==null)return "";return "https://i.iwara.tv/image/thumbnail/"+f.getString("id")+"/thumbnail-"+String.format(Locale.US,"%02d",n)+".jpg";} static String mark(String u,String page){return u+"#iwara=1&ref="+enc(page);} static Map<String,List<String>> h(){Map<String,List<String>>m=new HashMap<>();m.put("Accept",Collections.singletonList("application/json"));m.put("Content-Type",Collections.singletonList("application/json"));m.put("Referer",Collections.singletonList(WEB+"/"));m.put("Origin",Collections.singletonList(WEB));m.put("X-Site",Collections.singletonList("www.iwara.tv"));m.put("X-Version",Collections.singletonList(VERSION));m.put("User-Agent",Collections.singletonList("Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 Chrome/120.0 Mobile Safari/537.36"));return m;} static String enc(String x){try{return URLEncoder.encode(x,StandardCharsets.UTF_8.name());}catch(Exception e){throw new IllegalStateException(e);}}}
